
-- Drop existing policies if they exist to avoid duplication errors
drop policy if exists "Anyone can insert results" on quiz_results;
drop policy if exists "Public read access" on quiz_results;

-- Create the table if it doesn't already exist
create table if not exists quiz_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  personality_type text,
  career_1 text,
  career_2 text,
  career_3 text,
  traits text[],
  scores jsonb
);

-- Note: user_id removed to allow guest submissions. 
-- In a production app, you might want to add it back if you add authentication.

alter table quiz_results enable row level security;

-- Allow anyone to submit their quiz results (Lead generation)
create policy "Anyone can insert results"
  on quiz_results for insert
  with check (true);

-- For security, you might want to restrict viewing to a specific admin role or authenticated user_id
-- For now, allowing public read for simplicity in development, but consider hardening this!
create policy "Public read access"
  on quiz_results for select
  using (true);

